namespace CodeMentor.Domain.Assessments;

public enum SkillCategory
{
    DataStructures = 1,
    Algorithms = 2,
    OOP = 3,
    Databases = 4,
    Security = 5,
}

public enum Track
{
    FullStack = 1,
    Backend = 2,
    Python = 3,
}

public enum SkillLevel
{
    Beginner = 1,
    Intermediate = 2,
    Advanced = 3,
}

public enum AssessmentStatus
{
    InProgress = 1,
    Completed = 2,
    TimedOut = 3,
    Abandoned = 4,
}

// S21-T1 / F16 (ADR-049): which "kind" of assessment this row represents.
//   Initial  = the user's first-ever assessment (pre-S21 default — also the
//              30-question backfill for legacy rows). Triggers Path generation
//              + AI summary on completion.
//   Mini     = optional 10-question reassessment at 50% path progress. Draws
//              items NOT in any of the user's prior AssessmentResponses;
//              IRT theta seeded from LearnerSkillProfile. Does NOT trigger
//              path generation (mid-path); does NOT trigger AI summary.
//              EMA-updates LearnerSkillProfile (UpdateFromSubmissionAsync).
//   Full     = mandatory 30-question reassessment at 100% path completion;
//              gate for the "Generate Next Phase Path" CTA. Triggers AI
//              summary; OVERWRITES LearnerSkillProfile (re-anchor via
//              InitializeFromAssessmentAsync). Does NOT auto-trigger path
//              generation — gated by an explicit POST /learning-paths/me/next-phase.
public enum AssessmentVariant
{
    Initial = 1,
    Mini = 2,
    Full = 3,
}

// S15 / F15 (ADR-049 / ADR-050): provenance for the (a, b) parameters on
// a Question. AI = self-rated by the AI Generator at draft time
// (Sprint 16) or backfill default (S15-T4); Admin = manually set/overridden
// by an admin reviewer; Empirical = produced by the RecalibrateIRTJob
// once an item passes the >=1000-response threshold per ADR-055.
public enum CalibrationSource
{
    AI = 1,
    Admin = 2,
    Empirical = 3,
}

// S15 / F15 (ADR-049): provenance for the question content itself.
// Manual = hand-authored by team or imported from the original seed;
// AI = produced by the Sprint-16 AI Question Generator and approved
// through the admin drafts review flow.
public enum QuestionSource
{
    Manual = 1,
    AI = 2,
}

// S16 / F15 (ADR-049): state machine for a draft in the admin review flow.
// Draft = freshly generated by AI, awaiting review;
// Approved = admin accepted (with or without edits) → a Questions row exists;
// Rejected = admin rejected (with or without a reason) → no Questions row.
public enum QuestionDraftStatus
{
    Draft = 1,
    Approved = 2,
    Rejected = 3,
}
