-- Sprint 18 task-metadata backfill -- generated by run_task_backfill_s18.py
-- Per ADR-058 §1 (single-reviewer waiver) and ADR-049 §4 (default team review
-- amended by ADR-058 for S18 only), this is a deterministic per-category mapping.
-- Owner spot-check 5 random rows after apply per ADR-058 §4.
--
-- IMPORTANT: apply AFTER migration AddAiColumnsToTasks (S18-T1).
-- This script is idempotent: re-running overwrites SkillTagsJson + LearningGainJson
-- but does NOT touch the rest of the row.
SET XACT_ABORT ON;
BEGIN TRANSACTION;

UPDATE Tasks SET SkillTagsJson = N'[{"skill": "correctness", "weight": 0.6}, {"skill": "performance", "weight": 0.4}]',     LearningGainJson = N'{"correctness": 0.4, "performance": 0.3}' WHERE IsActive = 1 AND Category = N'DataStructures' AND SkillTagsJson IS NULL;
UPDATE Tasks SET SkillTagsJson = N'[{"skill": "correctness", "weight": 0.7}, {"skill": "performance", "weight": 0.3}]',     LearningGainJson = N'{"correctness": 0.5, "performance": 0.3}' WHERE IsActive = 1 AND Category = N'Algorithms' AND SkillTagsJson IS NULL;
UPDATE Tasks SET SkillTagsJson = N'[{"skill": "design", "weight": 0.6}, {"skill": "readability", "weight": 0.4}]',     LearningGainJson = N'{"design": 0.4, "readability": 0.3}' WHERE IsActive = 1 AND Category = N'OOP' AND SkillTagsJson IS NULL;
UPDATE Tasks SET SkillTagsJson = N'[{"skill": "correctness", "weight": 0.5}, {"skill": "performance", "weight": 0.3}, {"skill": "design", "weight": 0.2}]',     LearningGainJson = N'{"correctness": 0.4, "performance": 0.3, "design": 0.2}' WHERE IsActive = 1 AND Category = N'Databases' AND SkillTagsJson IS NULL;
UPDATE Tasks SET SkillTagsJson = N'[{"skill": "security", "weight": 0.7}, {"skill": "correctness", "weight": 0.3}]',     LearningGainJson = N'{"security": 0.5, "correctness": 0.3}' WHERE IsActive = 1 AND Category = N'Security' AND SkillTagsJson IS NULL;

COMMIT TRANSACTION;

-- Verification:
SELECT COUNT(*) AS BackfilledRowCount FROM Tasks WHERE IsActive = 1 AND SkillTagsJson IS NOT NULL AND LearningGainJson IS NOT NULL;
SELECT Category, COUNT(*) AS RowsPerCategory FROM Tasks WHERE IsActive = 1 AND SkillTagsJson IS NOT NULL GROUP BY Category ORDER BY Category;