"""S18-T2: backfill SkillTagsJson + LearningGainJson for the 21 existing
seed tasks via deterministic per-category mapping (no LLM cost; values are
defensible heuristics that the FE-side admin tool can later refine).

Per ADR-058 §1 (Sprint 18 single-reviewer waiver), Claude is the curator
for the backfill; the deterministic mapping below is the curated output.
Owner spot-check 5 random rows post-apply per ADR-058 §4.

Output:
- ``tools/seed-sprint18-task-backfill.sql`` — UPDATE statements + verification SELECT.

Run AFTER applying the AddAiColumnsToTasks migration (S18-T1).

Usage (from project root):
    .venv/Scripts/python ai-service/tools/run_task_backfill_s18.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent

# Per-category default skill tag distribution (weights sum to 1.0).
# Validated to satisfy the SkillTagsJson sum-to-one constraint (S18-T1 + S18-T3 schemas).
# Lists are intentionally short (1-3 tags) to mirror what the AI generator
# would propose at default difficulty.
CATEGORY_TAGS: dict[str, list[dict]] = {
    "DataStructures": [
        {"skill": "correctness", "weight": 0.6},
        {"skill": "performance", "weight": 0.4},
    ],
    "Algorithms": [
        {"skill": "correctness", "weight": 0.7},
        {"skill": "performance", "weight": 0.3},
    ],
    "OOP": [
        {"skill": "design", "weight": 0.6},
        {"skill": "readability", "weight": 0.4},
    ],
    "Databases": [
        {"skill": "correctness", "weight": 0.5},
        {"skill": "performance", "weight": 0.3},
        {"skill": "design", "weight": 0.2},
    ],
    "Security": [
        {"skill": "security", "weight": 0.7},
        {"skill": "correctness", "weight": 0.3},
    ],
}

# Per-category learning-gain estimate (each value in [0.0, 1.0]; keys match the tag skills).
# Reflects "if the learner completes this task, by how much does each skill grow?"
# Heuristic baseline; can be adjusted per-difficulty in a future iteration.
CATEGORY_GAIN: dict[str, dict[str, float]] = {
    "DataStructures": {"correctness": 0.4, "performance": 0.3},
    "Algorithms":     {"correctness": 0.5, "performance": 0.3},
    "OOP":            {"design": 0.4, "readability": 0.3},
    "Databases":      {"correctness": 0.4, "performance": 0.3, "design": 0.2},
    "Security":       {"security": 0.5, "correctness": 0.3},
}


def _sql_string(s: str) -> str:
    return "N'" + s.replace("'", "''") + "'"


def main() -> int:
    sql_lines = [
        "-- Sprint 18 task-metadata backfill -- generated by run_task_backfill_s18.py",
        "-- Per ADR-058 §1 (single-reviewer waiver) and ADR-049 §4 (default team review",
        "-- amended by ADR-058 for S18 only), this is a deterministic per-category mapping.",
        "-- Owner spot-check 5 random rows after apply per ADR-058 §4.",
        "--",
        "-- IMPORTANT: apply AFTER migration AddAiColumnsToTasks (S18-T1).",
        "-- This script is idempotent: re-running overwrites SkillTagsJson + LearningGainJson",
        "-- but does NOT touch the rest of the row.",
        "SET XACT_ABORT ON;",
        "BEGIN TRANSACTION;",
        "",
    ]

    for category, tags in CATEGORY_TAGS.items():
        gain = CATEGORY_GAIN[category]
        tags_json = json.dumps(tags, ensure_ascii=False)
        gain_json = json.dumps(gain, ensure_ascii=False)
        sql_lines.append(
            f"UPDATE Tasks "
            f"SET SkillTagsJson = {_sql_string(tags_json)}, "
            f"    LearningGainJson = {_sql_string(gain_json)} "
            f"WHERE IsActive = 1 AND Category = N'{category}' AND SkillTagsJson IS NULL;"
        )

    sql_lines += [
        "",
        "COMMIT TRANSACTION;",
        "",
        "-- Verification:",
        "SELECT COUNT(*) AS BackfilledRowCount FROM Tasks "
        "WHERE IsActive = 1 AND SkillTagsJson IS NOT NULL AND LearningGainJson IS NOT NULL;",
        "SELECT Category, COUNT(*) AS RowsPerCategory FROM Tasks "
        "WHERE IsActive = 1 AND SkillTagsJson IS NOT NULL "
        "GROUP BY Category ORDER BY Category;",
    ]

    out = REPO_ROOT / "tools" / "seed-sprint18-task-backfill.sql"
    out.write_text("\n".join(sql_lines), encoding="utf-8")

    print(f"Wrote {out.relative_to(REPO_ROOT)}")
    print(f"  {len(CATEGORY_TAGS)} UPDATE statements (one per category).")
    print("  Apply via: docker exec -i codementor-mssql /opt/mssql-tools18/bin/sqlcmd"
          " -S localhost -U sa -P $env:MSSQL_SA_PASSWORD -C -d CodeMentor -i"
          " /tmp/seed-sprint18-task-backfill.sql")
    return 0


if __name__ == "__main__":
    sys.exit(main())
