using CodeMentor.Domain.Assessments;

namespace CodeMentor.Infrastructure.Persistence.Seeds;

/// <summary>
/// 60 curated questions: 12 per category × 4 questions per difficulty across 1..3.
/// Each question has 4 options (A/B/C/D), a correct answer, and a short explanation.
/// </summary>
public static class QuestionSeedData
{
    public static IReadOnlyList<Question> All { get; } = new List<Question>
    {
        // ====================== DataStructures (12) ======================
        new() { Content = "Which of these operations is O(1) average-case on a hash table?",
            Difficulty = 1, Category = SkillCategory.DataStructures,
            Options = new[] { "A) Worst-case search", "B) Lookup by key", "C) Sort all entries", "D) Count collisions" },
            CorrectAnswer = "B",
            Explanation = "Hash tables provide O(1) average-case lookup by key. Worst-case is O(n) if many collisions." },
        new() { Content = "In a stack, elements are removed in which order?",
            Difficulty = 1, Category = SkillCategory.DataStructures,
            Options = new[] { "A) FIFO", "B) LIFO", "C) Random", "D) Priority" },
            CorrectAnswer = "B",
            Explanation = "Stack is LIFO: the last element pushed is the first one popped." },
        new() { Content = "What is the primary operation used to retrieve the next element from a queue?",
            Difficulty = 1, Category = SkillCategory.DataStructures,
            Options = new[] { "A) Push", "B) Peek", "C) Dequeue", "D) Sort" },
            CorrectAnswer = "C",
            Explanation = "Dequeue removes and returns the front of the queue (FIFO)." },
        new() { Content = "A singly linked list node typically contains which fields?",
            Difficulty = 1, Category = SkillCategory.DataStructures,
            Options = new[] { "A) Value only", "B) Value + next pointer", "C) Value + prev + next", "D) Left + right pointers" },
            CorrectAnswer = "B",
            Explanation = "A singly linked node has a value and a single 'next' pointer. Doubly-linked adds 'prev'." },
        new() { Content = "Finding the k-th smallest element in an unsorted array of n items using a min-heap takes what time?",
            Difficulty = 2, Category = SkillCategory.DataStructures,
            Options = new[] { "A) O(1)", "B) O(n)", "C) O(n log k)", "D) O(n²)" },
            CorrectAnswer = "C",
            Explanation = "Maintain a size-k heap while scanning n items; each insert/evict is O(log k) → O(n log k)." },
        new() { Content = "Which data structure is most appropriate to implement LRU cache with O(1) get and put?",
            Difficulty = 2, Category = SkillCategory.DataStructures,
            Options = new[] { "A) Sorted array", "B) Hash map + doubly-linked list", "C) Binary search tree", "D) Min-heap" },
            CorrectAnswer = "B",
            Explanation = "Hash map gives O(1) lookup; DLL gives O(1) removal/insert at arbitrary positions to update recency." },
        new() { Content = "Binary search on a sorted array of n elements has worst-case time complexity of:",
            Difficulty = 2, Category = SkillCategory.DataStructures,
            Options = new[] { "A) O(1)", "B) O(log n)", "C) O(n)", "D) O(n log n)" },
            CorrectAnswer = "B",
            Explanation = "Each step halves the search space, yielding log₂(n) steps." },
        new() { Content = "Which traversal visits a binary tree node AFTER both its children?",
            Difficulty = 2, Category = SkillCategory.DataStructures,
            Options = new[] { "A) Pre-order", "B) In-order", "C) Post-order", "D) Level-order" },
            CorrectAnswer = "C",
            Explanation = "Post-order = left, right, root — the root is visited last." },
        new() { Content = "A red-black tree guarantees which property?",
            Difficulty = 3, Category = SkillCategory.DataStructures,
            Options = new[] { "A) Perfect height balance", "B) No rotations ever needed", "C) O(log n) operations via approximate balance", "D) Constant-time deletion" },
            CorrectAnswer = "C",
            Explanation = "Red-black trees guarantee the longest path is at most 2× the shortest, giving O(log n)." },
        new() { Content = "In a disjoint-set (union-find) with path compression and union-by-rank, amortized cost per operation is:",
            Difficulty = 3, Category = SkillCategory.DataStructures,
            Options = new[] { "A) O(1)", "B) O(α(n)) (inverse Ackermann)", "C) O(log n)", "D) O(n)" },
            CorrectAnswer = "B",
            Explanation = "With both optimizations, the amortized cost is effectively constant — the inverse Ackermann α(n)." },
        new() { Content = "Which probing strategy most reduces primary clustering in open-addressed hash tables?",
            Difficulty = 3, Category = SkillCategory.DataStructures,
            Options = new[] { "A) Linear probing", "B) Quadratic probing", "C) Double hashing", "D) Chaining" },
            CorrectAnswer = "C",
            Explanation = "Double hashing uses a second hash for step size, spreading probes more evenly." },
        new() { Content = "A Bloom filter's false-positive rate increases primarily with:",
            Difficulty = 3, Category = SkillCategory.DataStructures,
            Options = new[] { "A) Item insertion order", "B) Bit-array size decreasing relative to items", "C) Number of hash functions > 10", "D) Using cryptographic hashes" },
            CorrectAnswer = "B",
            Explanation = "As the bit array fills relative to item count, more bits collide, raising false positives." },

        // ====================== Algorithms (12) ======================
        new() { Content = "Which sorting algorithm has the best average-case time complexity?",
            Difficulty = 1, Category = SkillCategory.Algorithms,
            Options = new[] { "A) Bubble sort", "B) Insertion sort", "C) Merge sort", "D) Selection sort" },
            CorrectAnswer = "C",
            Explanation = "Merge sort is O(n log n) average and worst case. Bubble/insertion/selection are O(n²)." },
        new() { Content = "What is the worst-case time complexity of quicksort?",
            Difficulty = 1, Category = SkillCategory.Algorithms,
            Options = new[] { "A) O(n)", "B) O(n log n)", "C) O(n²)", "D) O(log n)" },
            CorrectAnswer = "C",
            Explanation = "Quicksort degrades to O(n²) when pivots always split 1 vs n-1 (e.g., already-sorted input with naive pivot)." },
        new() { Content = "Which technique does merge sort use?",
            Difficulty = 1, Category = SkillCategory.Algorithms,
            Options = new[] { "A) Greedy", "B) Dynamic programming", "C) Divide and conquer", "D) Backtracking" },
            CorrectAnswer = "C",
            Explanation = "Split the array, sort each half, merge — classic divide-and-conquer." },
        new() { Content = "Breadth-first search (BFS) on a graph with n nodes and m edges runs in:",
            Difficulty = 1, Category = SkillCategory.Algorithms,
            Options = new[] { "A) O(n)", "B) O(m)", "C) O(n + m)", "D) O(n·m)" },
            CorrectAnswer = "C",
            Explanation = "BFS visits every node and edge once → O(n + m)." },
        new() { Content = "Dijkstra's algorithm requires what property of edge weights?",
            Difficulty = 2, Category = SkillCategory.Algorithms,
            Options = new[] { "A) Integer only", "B) Non-negative", "C) Unique", "D) Less than 100" },
            CorrectAnswer = "B",
            Explanation = "Dijkstra assumes non-negative edge weights; use Bellman-Ford if negatives are possible." },
        new() { Content = "The classic 0/1 knapsack problem is typically solved with which paradigm?",
            Difficulty = 2, Category = SkillCategory.Algorithms,
            Options = new[] { "A) Greedy", "B) Dynamic programming", "C) Divide and conquer", "D) Backtracking only" },
            CorrectAnswer = "B",
            Explanation = "DP builds a table of (item, capacity) subproblems — greedy is for the fractional knapsack." },
        new() { Content = "Which algorithm finds the shortest path in an unweighted graph?",
            Difficulty = 2, Category = SkillCategory.Algorithms,
            Options = new[] { "A) Depth-first search", "B) Breadth-first search", "C) A*", "D) Floyd-Warshall" },
            CorrectAnswer = "B",
            Explanation = "BFS visits nodes in increasing distance from the source, so first time each node is reached is the shortest path (unweighted)." },
        new() { Content = "Longest Common Subsequence on strings of length n and m has DP time complexity:",
            Difficulty = 2, Category = SkillCategory.Algorithms,
            Options = new[] { "A) O(n + m)", "B) O(n·m)", "C) O(n²·m²)", "D) O(2^n)" },
            CorrectAnswer = "B",
            Explanation = "Fill an n×m table, each cell O(1) work → O(n·m)." },
        new() { Content = "Floyd-Warshall computes all-pairs shortest paths in time:",
            Difficulty = 3, Category = SkillCategory.Algorithms,
            Options = new[] { "A) O(V + E)", "B) O(V² log V)", "C) O(V³)", "D) O(E · V log V)" },
            CorrectAnswer = "C",
            Explanation = "Three nested loops over V vertices → O(V³). Handles negative edges (no negative cycles)." },
        new() { Content = "The Master Theorem applies to recurrences of the form T(n) = aT(n/b) + f(n). Which case governs merge sort (a=2, b=2, f(n)=n)?",
            Difficulty = 3, Category = SkillCategory.Algorithms,
            Options = new[] { "A) Case 1 — f asymptotically smaller", "B) Case 2 — f polynomial-equal", "C) Case 3 — f asymptotically larger", "D) Doesn't apply" },
            CorrectAnswer = "B",
            Explanation = "log_b(a) = log₂(2) = 1; f(n) = n = Θ(n^1) matches case 2, giving T(n) = Θ(n log n)." },
        new() { Content = "Which problem class is NP-complete?",
            Difficulty = 3, Category = SkillCategory.Algorithms,
            Options = new[] { "A) Shortest path with non-negative weights", "B) Boolean satisfiability (SAT)", "C) Binary search", "D) Sorting n integers" },
            CorrectAnswer = "B",
            Explanation = "SAT was the first proven NP-complete problem (Cook-Levin). It's in NP and every NP problem reduces to it." },
        new() { Content = "A minimum spanning tree of a connected weighted graph can be found by:",
            Difficulty = 3, Category = SkillCategory.Algorithms,
            Options = new[] { "A) BFS only", "B) DFS only", "C) Kruskal's or Prim's algorithm", "D) Floyd-Warshall" },
            CorrectAnswer = "C",
            Explanation = "Kruskal (edges sorted + union-find) and Prim (grow tree from a start) both yield MSTs." },

        // ====================== OOP (12) ======================
        new() { Content = "Which OOP principle hides internal state behind a public interface?",
            Difficulty = 1, Category = SkillCategory.OOP,
            Options = new[] { "A) Inheritance", "B) Encapsulation", "C) Polymorphism", "D) Abstraction" },
            CorrectAnswer = "B",
            Explanation = "Encapsulation restricts direct access to internal state, exposing only a public API." },
        new() { Content = "In classical inheritance, a derived class typically has access to which base class members?",
            Difficulty = 1, Category = SkillCategory.OOP,
            Options = new[] { "A) Only public", "B) Public and protected", "C) All, including private", "D) None without casting" },
            CorrectAnswer = "B",
            Explanation = "Protected members are visible to derived classes; private members are not." },
        new() { Content = "Polymorphism enables which capability?",
            Difficulty = 1, Category = SkillCategory.OOP,
            Options = new[] { "A) Multiple inheritance", "B) Calling the same method on different types with different behavior", "C) Combining unrelated classes", "D) Skipping constructor calls" },
            CorrectAnswer = "B",
            Explanation = "Polymorphism lets a single interface represent different concrete implementations." },
        new() { Content = "What is an abstract class?",
            Difficulty = 1, Category = SkillCategory.OOP,
            Options = new[] { "A) A class with only private fields", "B) A class that cannot be instantiated directly", "C) A static class", "D) A class with no methods" },
            CorrectAnswer = "B",
            Explanation = "Abstract classes exist to be inherited; they often declare abstract methods that subclasses must implement." },
        new() { Content = "The Liskov Substitution Principle states:",
            Difficulty = 2, Category = SkillCategory.OOP,
            Options = new[] { "A) Classes should depend on abstractions", "B) A subtype should be substitutable for its base type without breaking correctness", "C) Don't repeat yourself", "D) Favor composition over inheritance" },
            CorrectAnswer = "B",
            Explanation = "LSP (Liskov) — derived classes must honor the base's behavioral contract." },
        new() { Content = "In the SOLID principles, what does 'D' stand for?",
            Difficulty = 2, Category = SkillCategory.OOP,
            Options = new[] { "A) Decoupling", "B) Dependency Inversion", "C) Data-hiding", "D) Domain-driven" },
            CorrectAnswer = "B",
            Explanation = "Dependency Inversion Principle: depend on abstractions, not concrete implementations." },
        new() { Content = "What design pattern ensures a class has only one instance with a global access point?",
            Difficulty = 2, Category = SkillCategory.OOP,
            Options = new[] { "A) Factory", "B) Singleton", "C) Observer", "D) Strategy" },
            CorrectAnswer = "B",
            Explanation = "Singleton controls instantiation so only one exists. Often overused — prefer DI-scoped lifetimes where possible." },
        new() { Content = "The Strategy pattern primarily achieves:",
            Difficulty = 2, Category = SkillCategory.OOP,
            Options = new[] { "A) Object creation flexibility", "B) Encapsulating interchangeable algorithms behind a common interface", "C) Notifying dependents of changes", "D) Chaining a sequence of operations" },
            CorrectAnswer = "B",
            Explanation = "Strategy swaps algorithms at runtime via a common interface — e.g., sort strategies, validation rules." },
        new() { Content = "Covariance and contravariance govern how generic types relate under inheritance. Which is correct for C#?",
            Difficulty = 3, Category = SkillCategory.OOP,
            Options = new[] { "A) `IEnumerable<out T>` is contravariant", "B) `Action<in T>` is covariant", "C) `IEnumerable<out T>` is covariant in T", "D) Interfaces can't be variant" },
            CorrectAnswer = "C",
            Explanation = "`IEnumerable<out T>` is covariant: `IEnumerable<Dog>` is assignable to `IEnumerable<Animal>`." },
        new() { Content = "Which scenario most suggests composition over inheritance?",
            Difficulty = 3, Category = SkillCategory.OOP,
            Options = new[] { "A) Two classes share 90% of behavior", "B) A class needs optional, swappable behaviors from orthogonal dimensions", "C) You want to mark a base class abstract", "D) Performance is critical" },
            CorrectAnswer = "B",
            Explanation = "When behaviors are orthogonal (e.g., storage + logging + validation), composing them avoids a combinatorial explosion of subclasses." },
        new() { Content = "In a class diagram, a filled diamond on one end of an association denotes:",
            Difficulty = 3, Category = SkillCategory.OOP,
            Options = new[] { "A) Aggregation", "B) Composition", "C) Inheritance", "D) Dependency" },
            CorrectAnswer = "B",
            Explanation = "Filled diamond = composition (strong whole-part, lifetime-bound). Hollow diamond = aggregation." },
        new() { Content = "Why does the Open/Closed Principle matter in practice?",
            Difficulty = 3, Category = SkillCategory.OOP,
            Options = new[] { "A) It reduces file count", "B) It allows extending behavior without modifying tested code", "C) It removes the need for tests", "D) It enforces single inheritance" },
            CorrectAnswer = "B",
            Explanation = "OCP: code should be open for extension (via new classes/strategies) but closed for modification, minimizing regressions." },

        // ====================== Databases (12) ======================
        new() { Content = "Which SQL clause filters rows before aggregation?",
            Difficulty = 1, Category = SkillCategory.Databases,
            Options = new[] { "A) HAVING", "B) WHERE", "C) GROUP BY", "D) ORDER BY" },
            CorrectAnswer = "B",
            Explanation = "WHERE filters rows before grouping. HAVING filters groups after aggregation." },
        new() { Content = "A primary key must be:",
            Difficulty = 1, Category = SkillCategory.Databases,
            Options = new[] { "A) Nullable", "B) Unique and non-null", "C) An integer", "D) Indexed manually" },
            CorrectAnswer = "B",
            Explanation = "Primary keys uniquely identify rows and cannot be null. Most DBMSs auto-index them." },
        new() { Content = "What is 1NF (First Normal Form)?",
            Difficulty = 1, Category = SkillCategory.Databases,
            Options = new[] { "A) No duplicate rows", "B) Atomic (indivisible) column values and a primary key", "C) No foreign keys", "D) No null values" },
            CorrectAnswer = "B",
            Explanation = "1NF: each column holds a single atomic value; tables have a primary key." },
        new() { Content = "An INNER JOIN returns:",
            Difficulty = 1, Category = SkillCategory.Databases,
            Options = new[] { "A) All rows from left table", "B) Only rows with matches in both tables", "C) All rows from both tables", "D) Only unmatched rows" },
            CorrectAnswer = "B",
            Explanation = "INNER JOIN returns only rows where the join condition matches in both tables." },
        new() { Content = "Which ACID property ensures committed transactions survive a system crash?",
            Difficulty = 2, Category = SkillCategory.Databases,
            Options = new[] { "A) Atomicity", "B) Consistency", "C) Isolation", "D) Durability" },
            CorrectAnswer = "D",
            Explanation = "Durability: once committed, changes persist through crashes (typically via write-ahead logs)." },
        new() { Content = "A non-clustered index typically stores:",
            Difficulty = 2, Category = SkillCategory.Databases,
            Options = new[] { "A) The full row inline", "B) A copy of the indexed columns + a row locator (e.g., clustered key or RID)", "C) A hash of the row", "D) Nothing — it's metadata only" },
            CorrectAnswer = "B",
            Explanation = "Non-clustered indexes store the indexed columns and a pointer back to the actual row." },
        new() { Content = "In 3NF (Third Normal Form), a table must not have:",
            Difficulty = 2, Category = SkillCategory.Databases,
            Options = new[] { "A) Any foreign keys", "B) Transitive dependencies between non-key columns", "C) Composite keys", "D) More than 10 columns" },
            CorrectAnswer = "B",
            Explanation = "3NF: non-key columns depend only on the key, not on other non-key columns." },
        new() { Content = "The READ COMMITTED isolation level prevents which anomaly?",
            Difficulty = 2, Category = SkillCategory.Databases,
            Options = new[] { "A) Dirty reads only", "B) Non-repeatable reads", "C) Phantom reads", "D) All of the above" },
            CorrectAnswer = "A",
            Explanation = "READ COMMITTED prevents dirty reads but still allows non-repeatable and phantom reads." },
        new() { Content = "A covering index for a query is one that:",
            Difficulty = 3, Category = SkillCategory.Databases,
            Options = new[] { "A) Covers the entire table", "B) Contains all columns needed by the query, avoiding a table lookup", "C) Is clustered", "D) Uses full-text search" },
            CorrectAnswer = "B",
            Explanation = "A covering index contains all SELECT'ed columns so the query plan skips the base table entirely." },
        new() { Content = "Which is the typical definition of the 'C' in CAP theorem?",
            Difficulty = 3, Category = SkillCategory.Databases,
            Options = new[] { "A) Commit atomicity", "B) Linearizable consistency — every read sees the most recent write", "C) Connection count", "D) Columnar storage" },
            CorrectAnswer = "B",
            Explanation = "CAP Consistency: every read sees the latest committed write (linearizability). Different from ACID's 'consistency'." },
        new() { Content = "Given a slow query, which is typically the FIRST diagnostic to inspect?",
            Difficulty = 3, Category = SkillCategory.Databases,
            Options = new[] { "A) Server RAM size", "B) Query execution plan and estimated vs actual rows", "C) Disk vendor", "D) Connection pool timeout" },
            CorrectAnswer = "B",
            Explanation = "The execution plan reveals missing indexes, bad joins, or stale statistics — the most common root causes." },
        new() { Content = "A SERIALIZABLE transaction under MVCC databases (e.g., Postgres) typically behaves as:",
            Difficulty = 3, Category = SkillCategory.Databases,
            Options = new[] { "A) Strict two-phase locking", "B) Serializable Snapshot Isolation (SSI) — detect and abort conflicting transactions", "C) Optimistic read-committed", "D) No isolation" },
            CorrectAnswer = "B",
            Explanation = "Postgres implements SERIALIZABLE via SSI — reads use snapshots, and the engine aborts transactions that would create non-serializable histories." },

        // ====================== Security (12) ======================
        new() { Content = "SQL injection is most effectively prevented by:",
            Difficulty = 1, Category = SkillCategory.Security,
            Options = new[] { "A) String escaping with replace()", "B) Parameterized queries / prepared statements", "C) Uppercase SQL keywords", "D) Renaming tables" },
            CorrectAnswer = "B",
            Explanation = "Parameterized queries separate SQL code from user data, making injection structurally impossible." },
        new() { Content = "HTTPS provides which guarantees?",
            Difficulty = 1, Category = SkillCategory.Security,
            Options = new[] { "A) Availability", "B) Confidentiality and integrity in transit", "C) Data backup", "D) Input validation" },
            CorrectAnswer = "B",
            Explanation = "TLS encrypts traffic (confidentiality) and authenticates it (integrity + server identity)." },
        new() { Content = "Which is considered the safest way to store user passwords?",
            Difficulty = 1, Category = SkillCategory.Security,
            Options = new[] { "A) Plaintext", "B) MD5 hash", "C) A slow, salted hash (Argon2, bcrypt, PBKDF2)", "D) Base64-encoded" },
            CorrectAnswer = "C",
            Explanation = "Slow, salted hashes resist offline brute-force and rainbow-table attacks. Argon2id is the current best practice." },
        new() { Content = "A Cross-Site Scripting (XSS) vulnerability allows an attacker to:",
            Difficulty = 1, Category = SkillCategory.Security,
            Options = new[] { "A) Read server files", "B) Execute JavaScript in other users' browsers", "C) Drop database tables", "D) Crash the server" },
            CorrectAnswer = "B",
            Explanation = "XSS injects script into pages viewed by other users, typically to steal cookies or perform actions on their behalf." },
        new() { Content = "CSRF is most effectively mitigated by:",
            Difficulty = 2, Category = SkillCategory.Security,
            Options = new[] { "A) Blocking GET requests", "B) SameSite cookies and/or anti-CSRF tokens on state-changing requests", "C) Rate limiting only", "D) HTTPS alone" },
            CorrectAnswer = "B",
            Explanation = "SameSite=Lax/Strict and CSRF tokens prevent cross-origin requests from silently reusing a user's session." },
        new() { Content = "JWTs should typically NOT be used to store:",
            Difficulty = 2, Category = SkillCategory.Security,
            Options = new[] { "A) User id", "B) Roles", "C) Highly sensitive data like PII or secrets (they're just base64, not encrypted)", "D) Issued-at timestamp" },
            CorrectAnswer = "C",
            Explanation = "A standard JWT is signed, not encrypted — the payload is readable by anyone who obtains the token." },
        new() { Content = "What is the purpose of a Content Security Policy (CSP) header?",
            Difficulty = 2, Category = SkillCategory.Security,
            Options = new[] { "A) Compress responses", "B) Restrict sources from which scripts, styles, and other resources may load", "C) Enforce rate limits", "D) Rotate TLS certs" },
            CorrectAnswer = "B",
            Explanation = "CSP reduces XSS impact by limiting allowed script/style origins. `script-src 'self'` is a strong default." },
        new() { Content = "The principle of least privilege dictates:",
            Difficulty = 2, Category = SkillCategory.Security,
            Options = new[] { "A) Admins should have no access", "B) Each component/user gets only the access it needs to do its job", "C) Applications should run as root for reliability", "D) Passwords must be changed every 30 days" },
            CorrectAnswer = "B",
            Explanation = "Least privilege minimizes blast radius when a component is compromised." },
        new() { Content = "When a user logs out, which of these is the best practice for handling a JWT refresh token?",
            Difficulty = 3, Category = SkillCategory.Security,
            Options = new[] { "A) Leave it active until expiry", "B) Revoke server-side (e.g., mark the token's hash revoked in the DB)", "C) Email the user a notification", "D) Store it in localStorage" },
            CorrectAnswer = "B",
            Explanation = "Refresh tokens must be revocable — a server-side revocation record prevents reuse after logout." },
        new() { Content = "An attacker submits a ZIP with a file named `../../etc/passwd`. What attack is this?",
            Difficulty = 3, Category = SkillCategory.Security,
            Options = new[] { "A) SQL injection", "B) Zip slip / path traversal", "C) CSRF", "D) XXE" },
            CorrectAnswer = "B",
            Explanation = "Zip slip exploits naive unzippers that don't validate entry paths against the extraction root, allowing writes outside." },
        new() { Content = "TLS certificate pinning primarily defends against:",
            Difficulty = 3, Category = SkillCategory.Security,
            Options = new[] { "A) Server CPU exhaustion", "B) Compromised/rogue Certificate Authorities issuing fraudulent certs for a domain", "C) SQL injection", "D) Brute-force password attacks" },
            CorrectAnswer = "B",
            Explanation = "Pinning restricts a client to accept only specific certs/keys for a host, defeating mis-issuance by malicious CAs." },
        new() { Content = "OAuth 2.0 'state' parameter exists to:",
            Difficulty = 3, Category = SkillCategory.Security,
            Options = new[] { "A) Speed up redirects", "B) Prevent CSRF on the authorize → callback flow (one-time unguessable value tied to the user's session)", "C) Select a permission scope", "D) Provide the refresh token" },
            CorrectAnswer = "B",
            Explanation = "The state param is an opaque, unguessable token the client verifies on callback — it confirms the response belongs to the initiated flow." },

    };
}
